services:
  ffmpeg-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://localhost:8000
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./temp:/app/temp
    restart: unless-stopped